import type { NextPage } from 'next'
import Head from 'next/head'
import { AppBar } from '../components/AppBar'
import { TransferSol } from '../components/TransferSol'
import { Loader } from '../components/Loader'
import { WalletContextProvider } from '../components/WalletContextProvider'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <WalletContextProvider>
                <AppBar />
                <div className={styles.FormContainer}>
                    <TransferSol />
                </div>
            </WalletContextProvider>
        </div>
    )
}

export default Home
